name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  app_name: docmanager

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Android App (Debug)
        run: ./gradlew :androidApp:assembleDebug
      - name: Naming Artifacts
        run: mv androidApp/build/outputs/apk/debug/*.apk androidApp/build/outputs/apk/debug/${{ env.app_name }}_${{ runner.os }}-Android-Debug_${{ github.run_number }}.apk
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v7
        with:
          path: androidApp/build/outputs/apk/debug/${{ env.app_name }}_${{ runner.os }}-Android-Debug_${{ github.run_number }}.apk
          archive: 'false'

  dmg-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DMG Package
        run: ./gradlew :desktopApp:packageDmg
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/dmg/*.dmg desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg
      - name: Removing quarantine attribute
        run: xattr -c desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg
          archive: 'false'

  dmg-intel:
    runs-on: macos-26-intel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DMG Package
        run: ./gradlew :desktopApp:packageDmg
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/dmg/*.dmg desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg
      - name: Removing quarantine attribute
        run: xattr -c desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg || true
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/dmg/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.dmg
          archive: 'false'

  deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DEB Package
        run: ./gradlew :desktopApp:packageDeb
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/deb/*.deb desktopApp/build/compose/binaries/main/deb/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.deb
      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/deb/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.deb
          archive: 'false'

  msi:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build MSI Package
        run: ./gradlew :desktopApp:packageMsi
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/msi/*.msi desktopApp/build/compose/binaries/main/msi/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.msi
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/msi/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.msi
          archive: 'false'

  exe:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build EXE Package
        run: ./gradlew :desktopApp:packageExe
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/exe/*.exe desktopApp/build/compose/binaries/main/exe/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.exe
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/exe/${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}.exe
          archive: 'false'

  distributable-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build EXE Distributable
        run: ./gradlew :desktopApp:createDistributable
      - name: Upload EXE Distributable Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.app_name }}_${{ runner.os }}-${{ runner.arch }}_${{ github.run_number }}
          path: desktopApp/build/compose/binaries/main/app/