name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  app_name: "docmanager"
  app_version: "1.1.0"

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Android App (Debug)
        run: ./gradlew :androidApp:assembleDebug
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.apk" >> $GITHUB_ENV
        env:
          RUNNER_OS: android
          RUNNER_ARCH: debug
      - name: Naming Artifacts
        run: mv androidApp/build/outputs/apk/debug/*.apk androidApp/build/outputs/apk/debug/${{ env.FILE_NAME }}
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v7
        with:
          path: androidApp/build/outputs/apk/debug/${{ env.FILE_NAME }}
          archive: 'false'

  dmg-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DMG Package
        run: ./gradlew :desktopApp:packageDmg
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.dmg" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/dmg/*.dmg desktopApp/build/compose/binaries/main/dmg/${{ env.FILE_NAME }}
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/dmg/${{ env.FILE_NAME }}
          archive: 'false'

  dmg-intel:
    runs-on: macos-26-intel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DMG Package
        run: ./gradlew :desktopApp:packageDmg
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.dmg" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/dmg/*.dmg desktopApp/build/compose/binaries/main/dmg/${{ env.FILE_NAME }}
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/dmg/${{ env.FILE_NAME }}
          archive: 'false'

  deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build DEB Package
        run: ./gradlew :desktopApp:packageDeb
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.deb" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/deb/*.deb desktopApp/build/compose/binaries/main/deb/${{ env.FILE_NAME }}
      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/deb/${{ env.FILE_NAME }}
          archive: 'false'

  msi:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build MSI Package
        run: ./gradlew :desktopApp:packageMsi
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.msi" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/msi/*.msi desktopApp/build/compose/binaries/main/msi/${{ env.FILE_NAME }}
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/msi/${{ env.FILE_NAME }}
          archive: 'false'

  msi-arm:
    runs-on: windows-11-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build MSI Package
        run: ./gradlew :desktopApp:packageMsi
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}.msi" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Naming Artifacts
        run: mv desktopApp/build/compose/binaries/main/msi/*.msi desktopApp/build/compose/binaries/main/msi/${{ env.FILE_NAME }}
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v7
        with:
          path: desktopApp/build/compose/binaries/main/msi/${{ env.FILE_NAME }}
          archive: 'false'

  distributable-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up latest JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: latest
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build EXE Distributable
        run: ./gradlew :desktopApp:createDistributable
      - name: Generate file name
        run: |
          echo "FILE_NAME=${{ env.app_name }}-${{ env.app_version }}+${{ github.run_number }}-${env.RUNNER_OS,,}-${env.RUNNER_ARCH,,}" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}
          RUNNER_ARCH: ${{ runner.arch }}
      - name: Upload EXE Distributable Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${env.FILE_NAME}
          path: desktopApp/build/compose/binaries/main/app/